// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBedf1v9I7VDU5cFJ6uBz82U3IKjGs9f_I',
    appId: '1:313506961077:web:369887b11bd1a1e3b750fc',
    messagingSenderId: '313506961077',
    projectId: 'taiktok-a5b77',
    authDomain: 'taiktok-a5b77.firebaseapp.com',
    storageBucket: 'taiktok-a5b77.firebasestorage.app',
    measurementId: 'G-9PLXV75S37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3appsSaLzwFPxiGCnDRG_ZibNBYGdFc',
    appId: '1:313506961077:android:560bb7639055c432b750fc',
    messagingSenderId: '313506961077',
    projectId: 'taiktok-a5b77',
    storageBucket: 'taiktok-a5b77.firebasestorage.app',
  );

}